services:
  - type: web
    name: calendrier-jdr
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false  # À configurer manuellement dans Render
      - key: SUPABASE_ANON_KEY
        sync: false  # À configurer manuellement dans Render 